### ISSUE TITLE
Objectif du site

### ISSUE THREAD

**Issue by arthaud-proust** [arthaud-proust/dev.arthaud.life#7]
Feedback Kévin :
"C'est quoi le but ? Dans un jeu t'as un objectif, là on ne sait pas."

Analyse du feedback :
- Ne sait pas forcément si c'est un jeu
- Ne connait pas d'objectif

**Comment by arthaud-proust** [comment]
## Actuellement
Pour l'instant _Life_ est surtout une démonstration de certaines des compétences que j'ai acquises. Elles sont majoritairement techniques :
- Séparation de la logique métier de la logique UI, ce qui me permet de tester le fonctionnel sans même avoir à lancer mon serveur, de choisir mon front au dernier moment car j'avais un jeu fonctionnel dans mon terminal.
- Utilisation du typescript pour ajouter de la clarté à mes données, améliorer la DX, avoir des interfaces pour brancher mon front ou d'autres parties sur mon coeur métier.
- TDD : Je réfléchis à ce que je veux ajouter en métier, j'écris mes tests selon les résultats attendus, puis je code pour valider les tests. En ayant mes tests en "watch" à coté de mon code j'ai un retour immédiat sur ce que je fait et d'éventuelles régressions.
- UX : analyse des retours utilisateurs, améliorations selon la pertinence ressentie des utilisateurs. Récupération des blocages majeurs, mais aussi analyse des blocages sous-jacents.

Cependant, le site n'a pas de but utilisateur. 
Je m'en rend compte lors de mes tests utilisateurs : je ne sais pas où je vais avec ce site. J'ai surtout envie de coder pour moi, pour apprendre, pour montrer ce que j'arrive à faire.
C'est la suite des compétences que je doit acquérir : après une solidification technique, je dois retourner m'intéresser aux utilisateurs, leurs besoins etc.

## Deux choix
Dans l'idée de travailler le côté business (réalité utilisateur, besoin) je peux convertir cette démonstration de compétences en une expérience interactive, un jeu.
C'est ce que j'ai commencé à faire avec un tutoriel, mais il faut ajouter un but, des récompenses, de la gamification...

Je peux aussi décider de continuer la démonstration de compétences technique en me concentrant sur un élargissement des fonctionnalités et donc les principes/patterns que j'utilise. Dans ce cas, _Life_ sera juste un placeholder et n'aura aucun but utilisateur si ce n'est d'être décoratif.

Dans les deux cas la codebase s'élargira, mais les compétences requises (et donc démontrées) ne seront pas les mêmes.

**Comment by arthaud-proust** [comment]
## Convertir ce projet en jeu

### Vocabulaire
- Cellule : case noire.
- Slot : case blanche.
- Grille : ensemble des _slot_ et des _cellules_.
- Organisme : organisations de _cellules_ qui a un comportement notable, utile, comme le planeur ou une porte logique
- Laboratoire : répertoire des _organismes_ découverts et maintenant réutilisables.
- Réserve : nombre de _cellules_ disponibles. Enlever une cellule de la grille augmente la réserve, ajouter une cellule sur la grille diminue la réserve.

### Buts
- Compétitif :  vivre le plus longtemps, étendre la grille le plus possible
- Exploratif : découvrir tous les _organismes_

### Règles
- [x] 3 cellules au départ (#14)
- [x] 100 tours maximum (#18)
- [x] Possibilité de faire pause/play à tout moment (#16)
- [x] Possibilité de retirer une cellule vivante pour la replacer ailleurs quand le jeu est en pause. (#16)
- [x] Fin du jeu s'il n'y a plus de cellule sur la grille. (#9)
- [x] La grille s'agrandit si une cellule vivante est sur un bord.

### Compétition
- [ ] Calcul de score : en fonction de quoi ? (#20)
- [ ] Leaderboard (#21)

### Découverte d'Organismes
- [ ] Liste des _organismes_ à découvrir (#25)
- [ ] Exemple : Lorsque le joueur fait un planeur pour la première fois, il a la possibilité d'en créer plus facilement depuis son _Laboratoire_
- [ ] Ajouter un _organisme_ à la _grille_ depuis le _laboratoire_ nécessite d'avoir assez de _cellules_ dans la _réserve_. (#25)
